version: "3"

services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "18000:8000"
    tty: true
    depends_on:
      - db
